version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres-wallet
    environment:
      POSTGRES_DB: "wallet_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  keydb:
    image: "eqalpha/keydb:x86_64_v5.3.3"
    container_name: keydb-wallet
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-wallet
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: